-- Seed demo reviews
insert into public.idea_reviews (
  id,
  created_at,
  author_name,
  idea_name,
  summary,
  owner_name,
  status,
  tags,
  category,
  competitors,
  proof,
  market_score,
  problem,
  improvement,
  evidence,
  wedge_score,
  core,
  out_of_scope,
  complexity,
  mvp_score,
  buyer,
  channel,
  message,
  proof_point,
  distribution_score,
  dependencies,
  kill_shot,
  mitigation,
  risk_score,
  is_demo
)
values
(
  '11111111-1111-1111-1111-111111111111',
  now() - interval '11 hours',
  'Dan',
  'Vertical documentation tool',
  'A documentation tool for SaaS teams that want AI-friendly product docs without enterprise bloat.',
  'Dan',
  'researching',
  'docs, b2b, ai-discovery',
  'Documentation / knowledge base SaaS',
  'GitBook, Document360, Help Scout Docs, Slab',
  'Clear pricing pages, active review presence, steady search demand for alternatives and migration help.',
  'strong',
  'Current tools are either too bloated, too expensive, or weak for public product documentation.',
  'A simpler, more opinionated docs product optimized for discoverability, speed, and AI readability.',
  'Repeated complaints about pricing, clunky editing, and publishing friction.',
  'strong',
  'Structured doc publishing, navigation, search, changelog pages, and public hosting.',
  'Complex permissions, deep analytics, enterprise workflows.',
  'Search quality and migration imports could expand scope if not constrained.',
  'medium',
  'Founders, product marketers, and devrel teams at 10-200 person SaaS companies.',
  'SEO and founder-led outbound',
  'Ship clearer product docs without enterprise bloat or overpriced seats.',
  'Live example docs site and competitor teardown.',
  'medium',
  'Hosting and search vendor, but limited platform dependency.',
  'Large incumbents could copy positioning, though not instantly.',
  'Keep scope tight and differentiate on workflow speed and publishing quality.',
  'medium',
  true
),
(
  '22222222-2222-2222-2222-222222222222',
  now() - interval '19 hours',
  'Team',
  'Consumer app dependent on one platform API',
  'An automation layer built almost entirely on top of one third-party social platform API.',
  'Team',
  'deferred',
  'consumer, platform-risk',
  'Social automation',
  'Several niche tools exist, but many have fragile histories.',
  'Users pay today, but ecosystem health is unstable.',
  'medium',
  'Users want easier automation and scheduling.',
  'Cleaner UX and bundled workflows.',
  'Complaints about complexity and churn among existing tools.',
  'medium',
  'Simple campaign builder and account management.',
  'Agency features and team workflows.',
  'Moderate.',
  'medium',
  'Solo creators and small teams.',
  'Influencer content and paid social.',
  'Manage social automation with less friction.',
  'Demo videos and templates.',
  'medium',
  'One major API provider and its policy surface.',
  'API policy or pricing change can wipe out the product.',
  'Very limited unless product broadens beyond the platform.',
  'weak',
  true
);

-- Seed demo comments
insert into public.idea_comments (
  created_at,
  review_id,
  author_name,
  body
)
values
(
  now() - interval '5 hours',
  '11111111-1111-1111-1111-111111111111',
  'Matt',
  'The wedge makes sense, but I would force us to prove a sharper first channel before approval.'
),
(
  now() - interval '12 hours',
  '22222222-2222-2222-2222-222222222222',
  'Kevin',
  'The platform kill-shot is too obvious. I would treat this as a learning exercise, not a company candidate.'
)
